# Getting Python


For this course, we are going to use Jupyter notebook as our environment for developing Python code.
refer to https://jupyter.readthedocs.io/en/latest/content-quickstart.html for the instructions on how to install it. The easiest way is to install from Anaconda (https://www.anaconda.com/download/) website, make sure you install with Python 3.6 or above.

Also, it is good for the students who are not familiar with python (or they need a quick refreshment) to follow Jim Bagrow tutorial http://bagrow.com/ds1/whirlwindtourpython/00-Title.html. 

All the assignments need to be written in Python 3.6 or above and can be run using Jupyter on Chrome, Safari or Firefox. These are the browsers that officially supported by jupyter.

<u> Note: for this assignment, submit your local copy of this page, running on IPython. Submit the file to Blackboard under Assignment1 using this file format:</u> <b>Yourfirstname_lastname_Assignment1.ipynb</b> 

#### <b>Deadline</b>: <u>Thursday, Sept-12-2019 11:59 PM.</u>


# Assignment 1

##### Always import all needed libraries in the first cell

In [13]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

### Part 1, Q1

1) Use the np.linspace function to create a row vector called Points containing exactly 499 values with values evenly spaced between -1 and 1.

2) What is the value at index 53?

In [14]:
#Your code here
Points = np.linspace(-1,1,499)
print(Points[53])



-0.7871485943775101


### Part 1, Q2 

For a given array x of 3x3 dimensions, convert this array into a one-dimensional array.

Hint: 1) The output should be [1 2 3 4 5 6 7 8 9].

2) To get the dimension of an array, we use shape property. The dimension of the resulted array should be 1x9.


In [15]:
x = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(x.shape)

#Your code here
np.reshape(x,(1,9))



(3, 3)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Part 1, Q3

Create an 10 x 10 array of zeros and then "frame" it with a border of ones(The framed array's size should be 10x10).

In [16]:
#Your code here
zeros = (10,10)
zeros = np.zeros(zeros)
np.pad(zeros,1,'constant',constant_values=1)



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Part 1, Q4


Create an 8 x 8 array with a checkerboard pattern of zeros and ones using for loop or vstack.
The expected output is given below:
      <h4> [[1, 0, 1, 0, 1, 0, 1, 0],</h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1], </h4>
      <h4> [1, 0, 1, 0, 1, 0, 1, 0], </h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1], </h4>
      <h4> [1, 0, 1, 0, 1, 0, 1, 0], </h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1], </h4>
      <h4> [1, 0, 1, 0, 1, 0, 1, 0], </h4>
      <h4> [0, 1, 0, 1, 0, 1, 0, 1]] </h4>
      
      

In [17]:
#Your code here
checkerBoard = np.zeros((8,8),dtype=int)

for index, line in enumerate(checkerBoard):
    if index % 2 == 0:
        for x in range(0,8,2):
            line[x] = 1
    else:
        for x in range(1,8,2):
            line[x] = 1
        
print(checkerBoard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### Part 1, Q5

Create a function which creates an n×n array with (i,j)-entry equal to i+j.Here i is the index of row and j is the index of column. For example, if the index of i is 2 and the index of j is 5, then, the value of i+j will be 7.

In [18]:
#Your code here
def nByn(x, y):
    matrix = np.zeros((x,y),dtype=int)
    for index, line in enumerate(matrix):
        for x in range(0,line.size):
            line[x] = index+x
    return matrix
       
result = nByn(8,8)
print(result)
    



[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


### Part 1, Q6


Define a matrix(2D array) of 100x100 and initialize this matrix by its row index. After that, define a vector(1D array) of length 100 and initialize this vector by the index of the element.

Now, Use the dot function on a vector-vector, matrix-vector and matrix-matrix example. you can define your own dot function or use any build in functions. Dot function should peform dot product of two arrays (in this case between 2D and 1D array).

Hint: One way of doing this is to use np.dot() function.
You can have a look at this link: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

In [19]:
#Your code here
matrix = nByn(100,100)
oneD = np.arange(100)

print("Vector/Vector = ",np.dot(oneD,oneD))
print("Vector/Matrix = ",np.dot(oneD,matrix))
print("Matrix/Matrix = ",np.dot(matrix,matrix))



Vector/Vector =  328350
Vector/Matrix =  [328350 333300 338250 343200 348150 353100 358050 363000 367950 372900
 377850 382800 387750 392700 397650 402600 407550 412500 417450 422400
 427350 432300 437250 442200 447150 452100 457050 462000 466950 471900
 476850 481800 486750 491700 496650 501600 506550 511500 516450 521400
 526350 531300 536250 541200 546150 551100 556050 561000 565950 570900
 575850 580800 585750 590700 595650 600600 605550 610500 615450 620400
 625350 630300 635250 640200 645150 650100 655050 660000 664950 669900
 674850 679800 684750 689700 694650 699600 704550 709500 714450 719400
 724350 729300 734250 739200 744150 749100 754050 759000 763950 768900
 773850 778800 783750 788700 793650 798600 803550 808500 813450 818400]
Matrix/Matrix =  [[ 328350  333300  338250 ...  808500  813450  818400]
 [ 333300  338350  343400 ...  823150  828200  833250]
 [ 338250  343400  348550 ...  837800  842950  848100]
 ...
 [ 808500  823150  837800 ... 2229550 2244200 2258850]
 [ 813

### Part 1, Q7

 For a given random 3x5 array using the np.random.randint() function,
 compute (without using for loop): the sum of all the entries, the sum of the rows and the sum of the columns. 

In [20]:
arr= np.random.randint(50, size=(3, 5))
#Your code here

total = np.sum(arr)
sumRows = np.sum(arr,axis=0)
sumCols = np.sum(arr,axis=1)

print("Total sum of values =",total)
print("Total sum of rows =",sumRows)
print("Total sum of columns =",sumCols)


Total sum of values = 397
Total sum of rows = [ 53  59 110  82  93]
Total sum of columns = [ 71 158 168]


### Part 1, Q8
In this question, a 5x5 array has been created using np.random.randint(). The goal is to sort(ascending) all the rows using the second column. To be more specific,to sort the rows, we will use the values from column 2.
Lets say you have an array like below:

[[46 36 40 40 25]

 [43  3 17 23  4]
 
 [43 39  7  9  4]
 
 After the sorting, you will have output like below:
 
 [43  3 17 23  4]
 
 [46 36 40 40 25]
 
 [43 39  7  9  4]
 

Hint: You can use argsort function. It is just a way. You can follow other way if you want.

In [21]:
x = np.random.randint(50, size=(5, 5))

print('Unsorted:\n{}\n'.format(x))
#Your code here

x = x[x[:,1].argsort()]

#--------------------
print('Rows sorted by the second column:\n{}'.format(x))

Unsorted:
[[35 41 29 41 20]
 [16 46 20  7 35]
 [31 36 30  9  3]
 [39 46 34 49 15]
 [36  6 45 46 47]]

Rows sorted by the second column:
[[36  6 45 46 47]
 [31 36 30  9  3]
 [35 41 29 41 20]
 [16 46 20  7 35]
 [39 46 34 49 15]]


# Part 2
For part2, you will be using the Breast Cancer Wisconsin (Diagnostic) Database to create a classifier that can help diagnose patients. First, read through the description of the dataset (below).

In [22]:
from sklearn.datasets import load_breast_cancer

The object returned by load_breast_cancer() is a scikit-learn Bunch object, which is similar to a dictionary, for information about dictionary refer to http://bagrow.com/ds1/whirlwindtourpython/07-Built-in-Data-Structures.html

In [23]:
cancer = load_breast_cancer()
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [24]:
cancer['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [25]:
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [26]:
cancer['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [27]:
cancer['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

#### Part2 - Q1

How many features does the breast cancer dataset have?
This function should return an integer.

In [28]:
#Your code here
def numFeatures():
    return len(cancer['feature_names'])

print(numFeatures())



30


#### Part2 - Q2

Scikit-learn is machine learning library for the Python programming language. 

Convert the sklearn.dataset cancer to a DataFrame.

This function should return a (569, 31) DataFrame with
columns =

['mean radius', 'mean texture', 'mean perimeter', 'mean area',
'mean smoothness', 'mean compactness', 'mean concavity',
'mean concave points', 'mean symmetry', 'mean fractal dimension',
'radius error', 'texture error', 'perimeter error', 'area error',
'smoothness error', 'compactness error', 'concavity error',
'concave points error', 'symmetry error', 'fractal dimension error',
'worst radius', 'worst texture', 'worst perimeter', 'worst area',
'worst smoothness', 'worst compactness', 'worst concavity',
'worst concave points', 'worst symmetry', 'worst fractal dimension',
'target']

In [29]:
#Your code here

def conversion():
      
    cols = np.append(cancer.feature_names, 'target');   
    index = pd.RangeIndex(start=0, stop=569, step=1);
    data = np.column_stack((cancer.data, cancer.target))
    
    # Create dataframe with keywords
    df = pd.DataFrame(data=data, index=index, columns=cols)
    
    return df


print(conversion())


Features Column Size: 31
Data Column Size: 31.0
     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0         17.990         10.38          122.80     1001.0          0.11840   
1         20.570         17.77          132.90     1326.0          0.08474   
2         19.690         21.25          130.00     1203.0          0.10960   
3         11.420         20.38           77.58      386.1          0.14250   
4         20.290         14.34          135.10     1297.0          0.10030   
5         12.450         15.70           82.57      477.1          0.12780   
6         18.250         19.98          119.60     1040.0          0.09463   
7         13.710         20.83           90.20      577.9          0.11890   
8         13.000         21.82           87.50      519.8          0.12730   
9         12.460         24.04           83.97      475.9          0.11860   
10        16.020         23.24          102.70      797.8          0.08206   
11        15.780

#### Part2 - Q3

What is the class distribution? (i.e. how many instances of malignant (encoded 0) and how many benign (encoded 1)?)
This function should return a Series of length 2 with integer values and index = ['malignant', 'benign']

In [ ]:
#Your code here




#### Part2 - Q4

Split the DataFrame into X (the data) and y (the labels).

This function should return a tuple of length 2: (X, y), where

- X has shape (569, 30)
- y has shape (569,).

for more information about tuple refer to http://bagrow.com/ds1/whirlwindtourpython/07-Built-in-Data-Structures.html

In [ ]:
#Your code here



#### Part2 - Q5
Plot the histogram of 'malignant' and 'benign'.

Histogram is way to show the frequency of a set of continuous data. In this case, there are 2 labels ('malignant' and 'benign').The name of the labels will be in the x-axis and the frequency count of those labels will be in the y-axis.

You can find more about Histogram here:

https://statistics.laerd.com/statistical-guides/understanding-histograms.php

In [ ]:
#Your code here

